version: "3.8"
services:
  ps_flag_flask:
    image: ps_flag:1.1
    restart: always
    container_name: "compose-ps-flag"
    volumes:
      - "./:/app:rw"
      - "/home/mary/wenshu/public:/home/mary/wenshu/public:rw"
      - "/home/mary/wenshu/celine:/home/mary/wenshu/celine:rw"
      - "/usr/lib/nltk_data:/usr/lib/nltk_data"
    environment:
      - FLASK_DEBUG=product
      - TEXT_PATH=/home/lx/workshop/PS_Plag
      - IP_PORT=106.14.171.72:6008
      - SCORE_ADDR=106.14.171.72:6008
      - C_FORCE_ROOT="true"
    command:
      - /bin/sh
      - -c
      - |
                export FLASK_APP=app && gunicorn -t 30000 -w 4 -b 0.0.0.0:8000 'app:create_app("dev")' & celery -A celery_tasks.main worker -l info -P eventlet -c 1000

    ports:
      - "9872:8000"
    networks:
      - app_net
  plag_activate_p:
    build: .
    image: ps_flag:1.1
    #    restart: always
    volumes:
      - "./:/app:rw"
    depends_on:
      - ps_flag_flask
    command:
      - /bin/sh
      - -c
      - |
        python activatePlag.py
    container_name: "plag_activate_p"
    networks:
      - app_net
  ps_plag_redis_pro:
    image: redis:latest
    restart: always
    container_name: "compose-ps_plagredispro"
    ports:
      - "6384:6379"
    command:
      - /bin/bash
      - -c
      - "redis-server"
#    volumes:
#      - ./data:/data
#      - ./conf/redis.conf:/etc/redis/redis.conf
    networks:
      - app_net

networks:
  app_net:
